name: ci

on:
  push:
    branches:
      -  "main"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
   
      - name: Checkout
        uses: actions/checkout@v3
     
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      -  name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
    
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/practice:latest
  job2:  
   name: AWS Stuff
  
   runs-on: ubuntu-latest
   steps: 
    
     - name: Checkouting
       uses: actions/checkout@v3

     - name: Installing  Node
       uses: actions/setup-node@v2
     - name: Install packages 
       run:   npm i --legacy-peer-deps
  
     - name: Login to AWS 
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_KEY }}
        aws-region: ap-south-1 
     - name: build 
       run : npm run build   
     - name: s3 deploy
       run : aws s3 sync  build/ s3://24-7entertainment  
     