name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
       docker build . --file Dockerfile --tag my-image-name:movies
       docker run --interactive -d -p 3010:3000  --tty --entrypoint /bin/sh movies
